baseURL = "https://ocaci.github.io/ocaci"
languageCode = "en-us"
title = "OCACI – Open Collective of AWS Certified Independents"
# theme removed; styling via Simple.css
enableGitInfo = true

# Pagination
[pagination]
  pagerSize = 10

[params]
  # Short description for the site meta
  description = "Open Collective directory of independent AWS-certified consultants."
  author = "Open Collective of AWS Certified Independents"
  # Show future-dated content
  showFuture = false

# Customize permalinks for the consultants section
[permalinks]
  consultants = "/consultants/:slug/"

# Define taxonomies if you plan to use categories or tags
[taxonomies]
  category = "categories"
  tag = "tags"

# Main site menu
[menu]

  [[menu.main]]
    name = "Submit Work"
    url = "/submit-work/"
    weight = 5

  [[menu.main]]
    name = "Consultants"
    url = "/consultants/"
    weight = 10

  [[menu.main]]
    name = "Joining"
    url = "/joining/"
    weight = 20

# Enable raw HTML (for redirects, etc.)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
