baseURL = "https://ocaci.github.io/ocaci"
languageCode = "en-us"
title = "OCACI – Open Collective of AWS Certified Independents"
# theme removed; styling via Simple.css
enableGitInfo = true

# Pagination
[pagination]
  pagerSize = 10

[params]
  # Short description for the site meta
  description = "Open Collective directory of independent AWS-certified consultants."
  author = "Open Collective of AWS Certified Independents"
  # Show future-dated content
  showFuture = false

# Customize permalinks for the consultants section
[permalinks]
  awscertifications = "/awscertifications/:title/"

# Define taxonomies if you plan to use categories or tags
[taxonomies]
  location = "locations"
  awscertifications = "awscertifications"

# Main site menu
[menu]

  [[menu.main]]
    name = "Hire a Consultant"
    url = "/hire/"
    weight = 5

  [[menu.main]]
    name = "Directory"
    url = "/consultants/"
    weight = 10

  [[menu.main]]
    name = "Joining OCACI"
    url = "/join/"
    weight = 20

# Enable raw HTML (for redirects, etc.)
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.extensions]
      attributes = true
    [markup.goldmark.renderer]
      unsafe = true
