name: Join OCACI
description: Request to join as a member of the Open Collective of AWS Certified Independents
title: "Join Request: [Your Name]"
body:
  - type: markdown
    attributes:
      value: |
        Please review and agree to our [Governance](https://github.com/ocaci/ocaci/blob/main/GOVERNANCE.md) and [Community Principles](https://github.com/ocaci/ocaci/blob/main/README.md) before joining OCACI.
  - type: input
    id: name
    attributes:
      label: Full Name
      placeholder: e.g., John Doe
    validations:
      required: true
  - type: input
    id: iq_profile
    attributes:
      label: AWS IQ Profile ID
      description: The expert ID from the IQ profile URL (https://iq.aws.amazon.com/e/expert-id)
      placeholder: e.g., johndoe
    validations:
      required: true
  - type: input
    id: github
    attributes:
      label: GitHub Username
      placeholder: e.g., johndoe123
    validations:
      required: true
  - type: checkboxes
    id: agree
    attributes:
      label: Governance and Community Principles
      description: "You must agree to follow the project's [Governance](https://github.com/ocaci/ocaci/blob/main/GOVERNANCE.md) and [Community Principles](https://github.com/ocaci/ocaci/blob/main/README.md)"
      options:
        - label: I agree to follow the project's governance and community principles.
          required: true
