name: Validate new profile on PR
permissions:
  contents: read
  issues: write
on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'content/consultants/*.md'
jobs:
  validate-profile:
    env:
      CHANGED_FILES: ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Poetry & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
        working-directory: scripts/python
      - name: Determine changed files
        id: changed
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- content/consultants/*.md)
          echo "CHANGED_FILES=$CHANGED" >> $GITHUB_ENV
      - name: Validate GitHub handle in front-matter
        if: env.CHANGED_FILES != ''
        run: |
          PR_AUTHOR=${{ github.event.pull_request.user.login }}
          for f in $CHANGED_FILES; do
<<<<<<< HEAD
<<<<<<< HEAD
            VAL=$(grep -E '^github:' "${GITHUB_WORKSPACE}/$f" | sed 's/^github:[[:space:]]*//')
=======
            VAL=$(grep -E '^github:' $f | sed 's/^github:[[:space:]]*//')
>>>>>>> 9b45a69 (ci: uppdate PR sync workflow)
=======
            VAL=$(grep -E '^github:' "${GITHUB_WORKSPACE}/$f" | sed 's/^github:[[:space:]]*//')
>>>>>>> eb3a80a (ci: uppdate PR sync workflow)
            if [ "$VAL" != "$PR_AUTHOR" ]; then
              echo "ERROR: front-matter github ($VAL) does not match PR author ($PR_AUTHOR)"
              exit 1
            fi
          done
      - name: Validate IQ profile by running sync_iq.py
        if: env.CHANGED_FILES != ''
        run: |
          for f in $CHANGED_FILES; do
            poetry run python sync_iq.py --files "$PWD/../../$f"
          done
        working-directory: scripts/python
